def buildDockerImage() {
    // Build Docker image
    dir('contacts.app.api-testing/ContactsApp') {
        sh 'docker build -t my-image1:latest .'
    }
}

pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                sh 'git clone https://github.com/FTdemo01/contacts.app.api-testing.git'
                sleep(30)
            }
        }

        stage('Check .NET SDK') {
            steps {
                sh 'dotnet --version'
            }
        }
        
        stage('Debug') {
            steps {
                sh 'ls -l'
            }
        }
        
        stage('Build') {
            steps {
                dir('contacts.app.api-testing/ContactsApp') {
                    sh 'dotnet build /p:Configuration=Release'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
            // Build Docker image
            buildDockerImage()
        }
        failure {
            echo 'Pipeline execution failed!'
        }
        always {
            cleanWs()
        }
    }
}