pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                sh 'git clone --branch main-docker https://github.com/FTdemo01/contacts.app.api-testing.git'
                sleep(30)
            }
        }

        stage('Check .NET SDK') {
            steps {
                sh 'dotnet --version'
            }
        }
        
        stage('Debug') {
            steps {
                sh 'ls -l'
            }
        }
        
        stage('Build') {
            steps {
                dir('contacts.app.api-testing/ContactsApp') {
                    sh 'dotnet build /p:Configuration=Release'
                }
            }
        }

        stage('Build docker') {
            steps {
                sh 'docker build -t my-image1:latest -f contacts.app.api-testing/ContactsApp/Dockerfile .'
                sh 'docker tag my-image1:latest 34.215.164.128/my-image1:latest'
                sh 'docker push 34.215.164.128/my-image1:latest'
            }
        }
      
    
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
           
        }
        failure {
            echo 'Pipeline execution failed!'
        }
        always {
            cleanWs()
        }
    }
}